# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rideMetrics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "rideMetrics.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11rideMetrics.proto" \n\x0btestRequest\x12\x11\n\tstartTest\x18\x01 \x01(\t"7\n\x0ctestResponse\x12\x12\n\ntestStatus\x18\x01 \x01(\t\x12\x13\n\x0btestStarted\x18\x02 \x01(\t2=\n\nRideMetric\x12/\n\x0epollTestStatus\x12\x0c.testRequest\x1a\r.testResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "rideMetrics_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_TESTREQUEST"]._serialized_start = 21
    _globals["_TESTREQUEST"]._serialized_end = 53
    _globals["_TESTRESPONSE"]._serialized_start = 55
    _globals["_TESTRESPONSE"]._serialized_end = 110
    _globals["_RIDEMETRIC"]._serialized_start = 112
    _globals["_RIDEMETRIC"]._serialized_end = 173
# @@protoc_insertion_point(module_scope)
