# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import rideMetrics_pb2 as rideMetrics__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in rideMetrics_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class RideMetricStub(object):
    """Main service for RideMetric"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.pollTestStatus = channel.unary_unary(
            "/RideMetric/pollTestStatus",
            request_serializer=rideMetrics__pb2.testRequest.SerializeToString,
            response_deserializer=rideMetrics__pb2.testResponse.FromString,
            _registered_method=True,
        )


class RideMetricServicer(object):
    """Main service for RideMetric"""

    def pollTestStatus(self, request, context):
        """This is a service for Ridemetric requests"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RideMetricServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "pollTestStatus": grpc.unary_unary_rpc_method_handler(
            servicer.pollTestStatus,
            request_deserializer=rideMetrics__pb2.testRequest.FromString,
            response_serializer=rideMetrics__pb2.testResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "RideMetric", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("RideMetric", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class RideMetric(object):
    """Main service for RideMetric"""

    @staticmethod
    def pollTestStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/RideMetric/pollTestStatus",
            rideMetrics__pb2.testRequest.SerializeToString,
            rideMetrics__pb2.testResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
